// Danh sách đầy đủ các quốc gia theo ISO 3166-1 alpha-2
export interface Country {
  code: string;
  name: string;
  nameVi: string;
}

export const COUNTRIES: Country[] = [
  { code: 'AD', name: 'Andorra', nameVi: 'Andorra' },
  {
    code: 'AE',
    name: 'United Arab Emirates',
    nameVi: 'Các Tiểu vương quốc Ả Rập Thống nhất',
  },
  { code: 'AF', name: 'Afghanistan', nameVi: 'Afghanistan' },
  { code: 'AG', name: 'Antigua and Barbuda', nameVi: 'Antigua và Barbuda' },
  { code: 'AI', name: 'Anguilla', nameVi: 'Anguilla' },
  { code: 'AL', name: 'Albania', nameVi: 'Albania' },
  { code: 'AM', name: 'Armenia', nameVi: 'Armenia' },
  { code: 'AO', name: 'Angola', nameVi: 'Angola' },
  { code: 'AQ', name: 'Antarctica', nameVi: 'Nam Cực' },
  { code: 'AR', name: 'Argentina', nameVi: 'Argentina' },
  { code: 'AS', name: 'American Samoa', nameVi: 'Samoa thuộc Mỹ' },
  { code: 'AT', name: 'Austria', nameVi: 'Áo' },
  { code: 'AU', name: 'Australia', nameVi: 'Australia' },
  { code: 'AW', name: 'Aruba', nameVi: 'Aruba' },
  { code: 'AX', name: 'Åland Islands', nameVi: 'Quần đảo Åland' },
  { code: 'AZ', name: 'Azerbaijan', nameVi: 'Azerbaijan' },
  {
    code: 'BA',
    name: 'Bosnia and Herzegovina',
    nameVi: 'Bosnia và Herzegovina',
  },
  { code: 'BB', name: 'Barbados', nameVi: 'Barbados' },
  { code: 'BD', name: 'Bangladesh', nameVi: 'Bangladesh' },
  { code: 'BE', name: 'Belgium', nameVi: 'Bỉ' },
  { code: 'BF', name: 'Burkina Faso', nameVi: 'Burkina Faso' },
  { code: 'BG', name: 'Bulgaria', nameVi: 'Bulgaria' },
  { code: 'BH', name: 'Bahrain', nameVi: 'Bahrain' },
  { code: 'BI', name: 'Burundi', nameVi: 'Burundi' },
  { code: 'BJ', name: 'Benin', nameVi: 'Benin' },
  { code: 'BL', name: 'Saint Barthélemy', nameVi: 'Saint Barthélemy' },
  { code: 'BM', name: 'Bermuda', nameVi: 'Bermuda' },
  { code: 'BN', name: 'Brunei Darussalam', nameVi: 'Brunei' },
  { code: 'BO', name: 'Bolivia', nameVi: 'Bolivia' },
  {
    code: 'BQ',
    name: 'Bonaire, Sint Eustatius and Saba',
    nameVi: 'Bonaire, Sint Eustatius và Saba',
  },
  { code: 'BR', name: 'Brazil', nameVi: 'Brazil' },
  { code: 'BS', name: 'Bahamas', nameVi: 'Bahamas' },
  { code: 'BT', name: 'Bhutan', nameVi: 'Bhutan' },
  { code: 'BV', name: 'Bouvet Island', nameVi: 'Đảo Bouvet' },
  { code: 'BW', name: 'Botswana', nameVi: 'Botswana' },
  { code: 'BY', name: 'Belarus', nameVi: 'Belarus' },
  { code: 'BZ', name: 'Belize', nameVi: 'Belize' },
  { code: 'CA', name: 'Canada', nameVi: 'Canada' },
  { code: 'CC', name: 'Cocos (Keeling) Islands', nameVi: 'Quần đảo Cocos' },
  {
    code: 'CD',
    name: 'Democratic Republic of the Congo',
    nameVi: 'Cộng hòa Dân chủ Congo',
  },
  {
    code: 'CF',
    name: 'Central African Republic',
    nameVi: 'Cộng hòa Trung Phi',
  },
  { code: 'CG', name: 'Congo', nameVi: 'Congo' },
  { code: 'CH', name: 'Switzerland', nameVi: 'Thụy Sĩ' },
  { code: 'CI', name: "Côte d'Ivoire", nameVi: 'Bờ Biển Ngà' },
  { code: 'CK', name: 'Cook Islands', nameVi: 'Quần đảo Cook' },
  { code: 'CL', name: 'Chile', nameVi: 'Chile' },
  { code: 'CM', name: 'Cameroon', nameVi: 'Cameroon' },
  { code: 'CN', name: 'China', nameVi: 'Trung Quốc' },
  { code: 'CO', name: 'Colombia', nameVi: 'Colombia' },
  { code: 'CR', name: 'Costa Rica', nameVi: 'Costa Rica' },
  { code: 'CU', name: 'Cuba', nameVi: 'Cuba' },
  { code: 'CV', name: 'Cape Verde', nameVi: 'Cape Verde' },
  { code: 'CW', name: 'Curaçao', nameVi: 'Curaçao' },
  { code: 'CX', name: 'Christmas Island', nameVi: 'Đảo Christmas' },
  { code: 'CY', name: 'Cyprus', nameVi: 'Síp' },
  { code: 'CZ', name: 'Czech Republic', nameVi: 'Cộng hòa Séc' },
  { code: 'DE', name: 'Germany', nameVi: 'Đức' },
  { code: 'DJ', name: 'Djibouti', nameVi: 'Djibouti' },
  { code: 'DK', name: 'Denmark', nameVi: 'Đan Mạch' },
  { code: 'DM', name: 'Dominica', nameVi: 'Dominica' },
  { code: 'DO', name: 'Dominican Republic', nameVi: 'Cộng hòa Dominica' },
  { code: 'DZ', name: 'Algeria', nameVi: 'Algeria' },
  { code: 'EC', name: 'Ecuador', nameVi: 'Ecuador' },
  { code: 'EE', name: 'Estonia', nameVi: 'Estonia' },
  { code: 'EG', name: 'Egypt', nameVi: 'Ai Cập' },
  { code: 'EH', name: 'Western Sahara', nameVi: 'Tây Sahara' },
  { code: 'ER', name: 'Eritrea', nameVi: 'Eritrea' },
  { code: 'ES', name: 'Spain', nameVi: 'Tây Ban Nha' },
  { code: 'ET', name: 'Ethiopia', nameVi: 'Ethiopia' },
  { code: 'FI', name: 'Finland', nameVi: 'Phần Lan' },
  { code: 'FJ', name: 'Fiji', nameVi: 'Fiji' },
  { code: 'FK', name: 'Falkland Islands', nameVi: 'Quần đảo Falkland' },
  { code: 'FM', name: 'Micronesia', nameVi: 'Micronesia' },
  { code: 'FO', name: 'Faroe Islands', nameVi: 'Quần đảo Faroe' },
  { code: 'FR', name: 'France', nameVi: 'Pháp' },
  { code: 'GA', name: 'Gabon', nameVi: 'Gabon' },
  { code: 'GB', name: 'United Kingdom', nameVi: 'Vương quốc Anh' },
  { code: 'GD', name: 'Grenada', nameVi: 'Grenada' },
  { code: 'GE', name: 'Georgia', nameVi: 'Georgia' },
  { code: 'GF', name: 'French Guiana', nameVi: 'Guiana thuộc Pháp' },
  { code: 'GG', name: 'Guernsey', nameVi: 'Guernsey' },
  { code: 'GH', name: 'Ghana', nameVi: 'Ghana' },
  { code: 'GI', name: 'Gibraltar', nameVi: 'Gibraltar' },
  { code: 'GL', name: 'Greenland', nameVi: 'Greenland' },
  { code: 'GM', name: 'Gambia', nameVi: 'Gambia' },
  { code: 'GN', name: 'Guinea', nameVi: 'Guinea' },
  { code: 'GP', name: 'Guadeloupe', nameVi: 'Guadeloupe' },
  { code: 'GQ', name: 'Equatorial Guinea', nameVi: 'Guinea Xích Đạo' },
  { code: 'GR', name: 'Greece', nameVi: 'Hy Lạp' },
  {
    code: 'GS',
    name: 'South Georgia and the South Sandwich Islands',
    nameVi: 'Nam Georgia và Quần đảo Nam Sandwich',
  },
  { code: 'GT', name: 'Guatemala', nameVi: 'Guatemala' },
  { code: 'GU', name: 'Guam', nameVi: 'Guam' },
  { code: 'GW', name: 'Guinea-Bissau', nameVi: 'Guinea-Bissau' },
  { code: 'GY', name: 'Guyana', nameVi: 'Guyana' },
  { code: 'HK', name: 'Hong Kong', nameVi: 'Hồng Kông' },
  {
    code: 'HM',
    name: 'Heard Island and McDonald Islands',
    nameVi: 'Đảo Heard và Quần đảo McDonald',
  },
  { code: 'HN', name: 'Honduras', nameVi: 'Honduras' },
  { code: 'HR', name: 'Croatia', nameVi: 'Croatia' },
  { code: 'HT', name: 'Haiti', nameVi: 'Haiti' },
  { code: 'HU', name: 'Hungary', nameVi: 'Hungary' },
  { code: 'ID', name: 'Indonesia', nameVi: 'Indonesia' },
  { code: 'IE', name: 'Ireland', nameVi: 'Ireland' },
  { code: 'IL', name: 'Israel', nameVi: 'Israel' },
  { code: 'IM', name: 'Isle of Man', nameVi: 'Đảo Man' },
  { code: 'IN', name: 'India', nameVi: 'Ấn Độ' },
  {
    code: 'IO',
    name: 'British Indian Ocean Territory',
    nameVi: 'Lãnh thổ Ấn Độ Dương thuộc Anh',
  },
  { code: 'IQ', name: 'Iraq', nameVi: 'Iraq' },
  { code: 'IR', name: 'Iran', nameVi: 'Iran' },
  { code: 'IS', name: 'Iceland', nameVi: 'Iceland' },
  { code: 'IT', name: 'Italy', nameVi: 'Italy' },
  { code: 'JE', name: 'Jersey', nameVi: 'Jersey' },
  { code: 'JM', name: 'Jamaica', nameVi: 'Jamaica' },
  { code: 'JO', name: 'Jordan', nameVi: 'Jordan' },
  { code: 'JP', name: 'Japan', nameVi: 'Nhật Bản' },
  { code: 'KE', name: 'Kenya', nameVi: 'Kenya' },
  { code: 'KG', name: 'Kyrgyzstan', nameVi: 'Kyrgyzstan' },
  { code: 'KH', name: 'Cambodia', nameVi: 'Campuchia' },
  { code: 'KI', name: 'Kiribati', nameVi: 'Kiribati' },
  { code: 'KM', name: 'Comoros', nameVi: 'Comoros' },
  { code: 'KN', name: 'Saint Kitts and Nevis', nameVi: 'Saint Kitts và Nevis' },
  { code: 'KP', name: 'North Korea', nameVi: 'Triều Tiên' },
  { code: 'KR', name: 'South Korea', nameVi: 'Hàn Quốc' },
  { code: 'KW', name: 'Kuwait', nameVi: 'Kuwait' },
  { code: 'KY', name: 'Cayman Islands', nameVi: 'Quần đảo Cayman' },
  { code: 'KZ', name: 'Kazakhstan', nameVi: 'Kazakhstan' },
  { code: 'LA', name: 'Laos', nameVi: 'Lào' },
  { code: 'LB', name: 'Lebanon', nameVi: 'Lebanon' },
  { code: 'LC', name: 'Saint Lucia', nameVi: 'Saint Lucia' },
  { code: 'LI', name: 'Liechtenstein', nameVi: 'Liechtenstein' },
  { code: 'LK', name: 'Sri Lanka', nameVi: 'Sri Lanka' },
  { code: 'LR', name: 'Liberia', nameVi: 'Liberia' },
  { code: 'LS', name: 'Lesotho', nameVi: 'Lesotho' },
  { code: 'LT', name: 'Lithuania', nameVi: 'Lithuania' },
  { code: 'LU', name: 'Luxembourg', nameVi: 'Luxembourg' },
  { code: 'LV', name: 'Latvia', nameVi: 'Latvia' },
  { code: 'LY', name: 'Libya', nameVi: 'Libya' },
  { code: 'MA', name: 'Morocco', nameVi: 'Morocco' },
  { code: 'MC', name: 'Monaco', nameVi: 'Monaco' },
  { code: 'MD', name: 'Moldova', nameVi: 'Moldova' },
  { code: 'ME', name: 'Montenegro', nameVi: 'Montenegro' },
  {
    code: 'MF',
    name: 'Saint Martin (French part)',
    nameVi: 'Saint Martin (phần Pháp)',
  },
  { code: 'MG', name: 'Madagascar', nameVi: 'Madagascar' },
  { code: 'MH', name: 'Marshall Islands', nameVi: 'Quần đảo Marshall' },
  { code: 'MK', name: 'North Macedonia', nameVi: 'Bắc Macedonia' },
  { code: 'ML', name: 'Mali', nameVi: 'Mali' },
  { code: 'MM', name: 'Myanmar', nameVi: 'Myanmar' },
  { code: 'MN', name: 'Mongolia', nameVi: 'Mông Cổ' },
  { code: 'MO', name: 'Macao', nameVi: 'Macao' },
  {
    code: 'MP',
    name: 'Northern Mariana Islands',
    nameVi: 'Quần đảo Bắc Mariana',
  },
  { code: 'MQ', name: 'Martinique', nameVi: 'Martinique' },
  { code: 'MR', name: 'Mauritania', nameVi: 'Mauritania' },
  { code: 'MS', name: 'Montserrat', nameVi: 'Montserrat' },
  { code: 'MT', name: 'Malta', nameVi: 'Malta' },
  { code: 'MU', name: 'Mauritius', nameVi: 'Mauritius' },
  { code: 'MV', name: 'Maldives', nameVi: 'Maldives' },
  { code: 'MW', name: 'Malawi', nameVi: 'Malawi' },
  { code: 'MX', name: 'Mexico', nameVi: 'Mexico' },
  { code: 'MY', name: 'Malaysia', nameVi: 'Malaysia' },
  { code: 'MZ', name: 'Mozambique', nameVi: 'Mozambique' },
  { code: 'NA', name: 'Namibia', nameVi: 'Namibia' },
  { code: 'NC', name: 'New Caledonia', nameVi: 'New Caledonia' },
  { code: 'NE', name: 'Niger', nameVi: 'Niger' },
  { code: 'NF', name: 'Norfolk Island', nameVi: 'Đảo Norfolk' },
  { code: 'NG', name: 'Nigeria', nameVi: 'Nigeria' },
  { code: 'NI', name: 'Nicaragua', nameVi: 'Nicaragua' },
  { code: 'NL', name: 'Netherlands', nameVi: 'Hà Lan' },
  { code: 'NO', name: 'Norway', nameVi: 'Na Uy' },
  { code: 'NP', name: 'Nepal', nameVi: 'Nepal' },
  { code: 'NR', name: 'Nauru', nameVi: 'Nauru' },
  { code: 'NU', name: 'Niue', nameVi: 'Niue' },
  { code: 'NZ', name: 'New Zealand', nameVi: 'New Zealand' },
  { code: 'OM', name: 'Oman', nameVi: 'Oman' },
  { code: 'PA', name: 'Panama', nameVi: 'Panama' },
  { code: 'PE', name: 'Peru', nameVi: 'Peru' },
  { code: 'PF', name: 'French Polynesia', nameVi: 'Polynesia thuộc Pháp' },
  { code: 'PG', name: 'Papua New Guinea', nameVi: 'Papua New Guinea' },
  { code: 'PH', name: 'Philippines', nameVi: 'Philippines' },
  { code: 'PK', name: 'Pakistan', nameVi: 'Pakistan' },
  { code: 'PL', name: 'Poland', nameVi: 'Ba Lan' },
  {
    code: 'PM',
    name: 'Saint Pierre and Miquelon',
    nameVi: 'Saint Pierre và Miquelon',
  },
  { code: 'PN', name: 'Pitcairn', nameVi: 'Pitcairn' },
  { code: 'PR', name: 'Puerto Rico', nameVi: 'Puerto Rico' },
  { code: 'PS', name: 'Palestine', nameVi: 'Palestine' },
  { code: 'PT', name: 'Portugal', nameVi: 'Bồ Đào Nha' },
  { code: 'PW', name: 'Palau', nameVi: 'Palau' },
  { code: 'PY', name: 'Paraguay', nameVi: 'Paraguay' },
  { code: 'QA', name: 'Qatar', nameVi: 'Qatar' },
  { code: 'RE', name: 'Réunion', nameVi: 'Réunion' },
  { code: 'RO', name: 'Romania', nameVi: 'Romania' },
  { code: 'RS', name: 'Serbia', nameVi: 'Serbia' },
  { code: 'RU', name: 'Russia', nameVi: 'Nga' },
  { code: 'RW', name: 'Rwanda', nameVi: 'Rwanda' },
  { code: 'SA', name: 'Saudi Arabia', nameVi: 'Ả Rập Saudi' },
  { code: 'SB', name: 'Solomon Islands', nameVi: 'Quần đảo Solomon' },
  { code: 'SC', name: 'Seychelles', nameVi: 'Seychelles' },
  { code: 'SD', name: 'Sudan', nameVi: 'Sudan' },
  { code: 'SE', name: 'Sweden', nameVi: 'Thụy Điển' },
  { code: 'SG', name: 'Singapore', nameVi: 'Singapore' },
  { code: 'SH', name: 'Saint Helena', nameVi: 'Saint Helena' },
  { code: 'SI', name: 'Slovenia', nameVi: 'Slovenia' },
  {
    code: 'SJ',
    name: 'Svalbard and Jan Mayen',
    nameVi: 'Svalbard và Jan Mayen',
  },
  { code: 'SK', name: 'Slovakia', nameVi: 'Slovakia' },
  { code: 'SL', name: 'Sierra Leone', nameVi: 'Sierra Leone' },
  { code: 'SM', name: 'San Marino', nameVi: 'San Marino' },
  { code: 'SN', name: 'Senegal', nameVi: 'Senegal' },
  { code: 'SO', name: 'Somalia', nameVi: 'Somalia' },
  { code: 'SR', name: 'Suriname', nameVi: 'Suriname' },
  { code: 'SS', name: 'South Sudan', nameVi: 'Nam Sudan' },
  { code: 'ST', name: 'Sao Tome and Principe', nameVi: 'Sao Tome và Principe' },
  { code: 'SV', name: 'El Salvador', nameVi: 'El Salvador' },
  {
    code: 'SX',
    name: 'Sint Maarten (Dutch part)',
    nameVi: 'Sint Maarten (phần Hà Lan)',
  },
  { code: 'SY', name: 'Syria', nameVi: 'Syria' },
  { code: 'SZ', name: 'Eswatini', nameVi: 'Eswatini' },
  {
    code: 'TC',
    name: 'Turks and Caicos Islands',
    nameVi: 'Quần đảo Turks và Caicos',
  },
  { code: 'TD', name: 'Chad', nameVi: 'Chad' },
  {
    code: 'TF',
    name: 'French Southern Territories',
    nameVi: 'Lãnh thổ phía Nam thuộc Pháp',
  },
  { code: 'TG', name: 'Togo', nameVi: 'Togo' },
  { code: 'TH', name: 'Thailand', nameVi: 'Thái Lan' },
  { code: 'TJ', name: 'Tajikistan', nameVi: 'Tajikistan' },
  { code: 'TK', name: 'Tokelau', nameVi: 'Tokelau' },
  { code: 'TL', name: 'Timor-Leste', nameVi: 'Timor-Leste' },
  { code: 'TM', name: 'Turkmenistan', nameVi: 'Turkmenistan' },
  { code: 'TN', name: 'Tunisia', nameVi: 'Tunisia' },
  { code: 'TO', name: 'Tonga', nameVi: 'Tonga' },
  { code: 'TR', name: 'Turkey', nameVi: 'Thổ Nhĩ Kỳ' },
  { code: 'TT', name: 'Trinidad and Tobago', nameVi: 'Trinidad và Tobago' },
  { code: 'TV', name: 'Tuvalu', nameVi: 'Tuvalu' },
  { code: 'TW', name: 'Taiwan', nameVi: 'Đài Loan' },
  { code: 'TZ', name: 'Tanzania', nameVi: 'Tanzania' },
  { code: 'UA', name: 'Ukraine', nameVi: 'Ukraine' },
  { code: 'UG', name: 'Uganda', nameVi: 'Uganda' },
  {
    code: 'UM',
    name: 'United States Minor Outlying Islands',
    nameVi: 'Các đảo nhỏ xa của Hoa Kỳ',
  },
  { code: 'US', name: 'United States', nameVi: 'Hoa Kỳ' },
  { code: 'UY', name: 'Uruguay', nameVi: 'Uruguay' },
  { code: 'UZ', name: 'Uzbekistan', nameVi: 'Uzbekistan' },
  { code: 'VA', name: 'Vatican City', nameVi: 'Vatican' },
  {
    code: 'VC',
    name: 'Saint Vincent and the Grenadines',
    nameVi: 'Saint Vincent và Grenadines',
  },
  { code: 'VE', name: 'Venezuela', nameVi: 'Venezuela' },
  {
    code: 'VG',
    name: 'British Virgin Islands',
    nameVi: 'Quần đảo Virgin thuộc Anh',
  },
  {
    code: 'VI',
    name: 'U.S. Virgin Islands',
    nameVi: 'Quần đảo Virgin thuộc Mỹ',
  },
  { code: 'VN', name: 'Vietnam', nameVi: 'Việt Nam' },
  { code: 'VU', name: 'Vanuatu', nameVi: 'Vanuatu' },
  { code: 'WF', name: 'Wallis and Futuna', nameVi: 'Wallis và Futuna' },
  { code: 'WS', name: 'Samoa', nameVi: 'Samoa' },
  { code: 'YE', name: 'Yemen', nameVi: 'Yemen' },
  { code: 'YT', name: 'Mayotte', nameVi: 'Mayotte' },
  { code: 'ZA', name: 'South Africa', nameVi: 'Nam Phi' },
  { code: 'ZM', name: 'Zambia', nameVi: 'Zambia' },
  { code: 'ZW', name: 'Zimbabwe', nameVi: 'Zimbabwe' },
];

// Helper functions
export const getCountryByCode = (code: string): Country | undefined => {
  return COUNTRIES.find((country) => country.code === code.toUpperCase());
};

export const getCountryName = (code: string, useVietnamese = false): string => {
  const country = getCountryByCode(code);
  if (!country) return code;
  return useVietnamese ? country.nameVi : country.name;
};

export const getCountryCodes = (): string[] => {
  return COUNTRIES.map((country) => country.code);
};

// Top SEO markets - các thị trường SEO phổ biến nhất
export const TOP_SEO_MARKETS = [
  'US',
  'GB',
  'CA',
  'AU',
  'DE',
  'FR',
  'ES',
  'IT',
  'NL',
  'SE',
  'NO',
  'DK',
  'FI',
  'BE',
  'AT',
  'CH',
  'IE',
  'PT',
  'PL',
  'CZ',
  'BR',
  'MX',
  'AR',
  'CO',
  'CL',
  'PE',
  'JP',
  'KR',
  'CN',
  'IN',
  'SG',
  'MY',
  'TH',
  'PH',
  'ID',
  'VN',
  'HK',
  'TW',
  'ZA',
  'EG',
  'IL',
  'AE',
  'SA',
  'TR',
  'RU',
  'UA',
  'GR',
  'RO',
  'BG',
  'HR',
];
